name: Release and Deploy TimbrApp Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ARTIFACT_NAME: "timbrapp-extension"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Package Extension (.zip)
        id: package-extension
        run: |
          ls -la
          mv src $ARTIFACT_NAME
          ls -la
          zip -r $ARTIFACT_NAME.zip $ARTIFACT_NAME
          ls -la

      - name: Create GitHub Release
        id: create-release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            New release TimbraApp Extension.
            **Version:** ${{ github.ref_name }}

      - name: Upload Zip to Release
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./$ARTIFACT_NAME.zip
          asset_name: $ARTIFACT_NAME.zip
          asset_content_type: application/zip
