name: Release and Deploy TimbrApp Extension

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ARTIFACT_NAME: "timbrapp-extension"

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Package
        id: package
        run: |
          mv src ${{ env.ARTIFACT_NAME }}
          zip -r ${{ env.ARTIFACT_NAME }}.zip ${{ env.ARTIFACT_NAME }}

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            A new TimbrApp release is here! 
            **Version:** ${{ github.ref_name }}
            Download the ZIP, extract the files, and load the extension in Chrome/Edge (make sure developer mode is enabled).
          draft: false
          prerelease: false
          files: |
            ./${{ env.ARTIFACT_NAME }}.zip
