name: Release and Deploy TimbrApp Extension

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ARTIFACT_NAME: "timbrapp-extension"
      DEBUG_MODE: ${{ github.ref_type == 'tag' && 'false' || 'true' }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      # - name: Setup Debug Mode
      #   id: debug-mode
      #   if: env.DEBUG_MODE == 'false'
      #   run: |
      #     sed -i "s/const DEBUG_MODE = .*/const DEBUG_MODE = $DEBUG_MODE;/g" $ARTIFACT_NAME/background.js

      # - name: Minify
      #   id: minify
      #   if: env.DEBUG_MODE == 'false'
      #   uses: nizarmah/auto-minify@v3
      #   with:
      #     directory: src
      #     output: src
      #     overwrite: true

      - name: Package
        id: package
        run: |
          mv src $ARTIFACT_NAME
          sed -i "s/const DEBUG_MODE = .*/const DEBUG_MODE = $DEBUG_MODE;/g" $ARTIFACT_NAME/background.js
          cp LICENSE $ARTIFACT_NAME
          curl -sL https://github.com/tdewolff/minify/releases/download/v2.21.3/minify_linux_amd64.tar.gz
          tar -xzf minify_linux_amd64.tar.gz
          chmod +x ./minify
          ./minify -r -o $ARTIFACT_NAME/ $ARTIFACT_NAME/
          zip -r $ARTIFACT_NAME.zip $ARTIFACT_NAME

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: TimbrApp Extension ${{ github.ref_name }}
          body: |
            The **TimbrApp Extension ${{ github.ref_name }}** release is here! 🎉
            Download the `${{ env.ARTIFACT_NAME }}.zip` file below, extract it, and load the extension in *developer mode* on Chrome/Edge.
          draft: false
          prerelease: false
          files: |
            ./${{ env.ARTIFACT_NAME }}.zip
