name: Release and Deploy TimbrApp Extension

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ARTIFACT_NAME: "timbrapp-extension"

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Package
        id: package
        run: |
          mv src ${{ env.ARTIFACT_NAME }}
          cp LICENSE ${{ env.ARTIFACT_NAME }}
          zip -r ${{ env.ARTIFACT_NAME }}.zip ${{ env.ARTIFACT_NAME }}

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: TimbrApp Extension ${{ github.ref_name }}
          body: |
            The **TimbrApp Extension ${{ github.ref_name }}** release is here! 🎉
            Download the ${{ env.ARTIFACT_NAME }}.zip file below, extract it, and load the extension in *developer mode* on Chrome/Edge.
          draft: false
          prerelease: false
          files: |
            ./${{ env.ARTIFACT_NAME }}.zip
